package com.tapan.twaktotest.domain.model

import com.google.gson.annotations.SerializedName

data class User(
    val avatarUrl: String,
    val eventsUrl: String,
    val followersUrl: String,
    val followingUrl: String,
    val gistsUrl: String,
    val gravatarId: String,
    val htmlUrl: String,
    val id: Int,
    val login: String,
    val nodeId: String,
    val organizationsUrl: String,
    val receivedEventsUrl: String,
    val reposUrl: String,
    val siteAdmin: Boolean,
    val starredUrl: String,
    val subscriptionsUrl: String,
    val type: String,
    val url: String,
    val note: String?,

    val bio: String? = null,
    val blog: String? = null,
    val company: String? = null,
    val createdAt: String? = null,
    val email: String? = null,
    val followers: Int? = null,
    val following: Int? = null,
    val hireable: String? = null,
    val location: String? = null,
    val name: String? = null,
    val publicGists: Int? = null,
    val publicRepos: Int? = null,
    val twitterUsername: String?,
    val updatedAt: String? = null,
)